// solid-accountant/src/app/auth/auth.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.scss']
})
export class AuthComponent implements OnInit {
  readonly providers: AuthProviderProps[] = [
    {
        url: 'https://inrupt.net',
        imgUrl: './assets/logos/inrupt.png',
        label: 'inrupt.net'
    },
    {
        url: 'https://solidcommunity.net/',
        imgUrl: './assets/logos/solid.svg',
        label: 'solidcommunity.net'
    },
    {
      url: 'http://localhost:3000/',
      imgUrl: './assets/logos/solid.svg',
      label: 'Local Solid Docker'
  }
]

  constructor() { }

  ngOnInit(): void {
  }

}

export interface AuthProviderProps {
  url: string;
  imgUrl: string;
  label?: string;
}
<div class="row pt-3">
    <div class="col">
        <h5>Log in</h5>
        <div class="description">Select an auth provider to log in</div>
    </div>
</div>
<div class="row pt-2">
    <div class="col">
        <div class="providers">
            <div *ngFor="let p of providers">
                <app-login-btn [provider]="p"></app-login-btn>
            </div>
        </div>
    </div>
</div>

// solid-accountant/src/pages/auth/auth.component.tsx
import React from "react";
import { Col, Container, Row } from "react-bootstrap";
import { AuthProvider, AuthProviderProps } from "../../components/auth-provider/auth-provider.component";

import "./auth.component.scss";

import inruptLogo from './logos/inrupt.png'
import solidLogo from './logos/solid.svg'

const providers: AuthProviderProps[] = [
    {
        url: 'https://inrupt.net',
        imgUrl: inruptLogo,
        label: 'inrupt.net'
    },
    {
        url: 'https://solidcommunity.net/',
        imgUrl: solidLogo,
        label: 'solidcommunity.net'
    }
]

export const Auth: React.FC = () => {

    return (
        <Container fluid="lg">
            <Row className="pt-3">
                <Col>
                    <h5>Log in</h5>
                    <div className="description">Select an auth provider to log in</div>
                </Col>
            </Row>
            <Row className="pt-2">
                <Col>
                    <div className="providers">
                        {providers.map((p,idx) => {
                            return <AuthProvider {...p} key={'auth-'+idx} />
                        })}
                    </div>
                </Col>
            </Row>
        </Container>
    );
}
